server:
  # 服务端口号
  port: 9000

spring:
  # 应用名称
  application:
    name: management
  # 数据库配置(Druid)
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?userUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: password
      # 初始连接数
      initial-size: 1
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 100
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 100000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 100000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      #安全配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: wslioy1920
      # 过滤配置
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # redis配置
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    #连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/com/yww/management/mapper/xml/*.xml